### ISSUE TITLE
Support for LetsEncrypt

### ISSUE THREAD

**Issue by athenawisdoms** [boschkundendienst/guacamole-docker-compose#10]
Awesome work, got up and running in a minute!

However, the self-signed certs are inconvenient and I dont have my own certificates. Since nginx is already included in the docker compose stack, can we please have support for generating and automatic renewing of LetsEncrypt certs?

This will make it even more amazing! Thanks :)

**Comment by boschkundendienst** [comment]
Thanks for your feedback. I created this repo to be able to test guacamole quick and easy which seems to work quite well. I can not assume that all installations have direct internet connection and the necessary ports forwarded to nginx which is a requirement for letsencrypt to work. But because I just use the standard nginx container and all customizations to it are only done by `prepare.sh` it would be easy for you to exchange `nginx` section in `docker-compose.yml` with an nginx image that supports letsencrypt directly e.g. `https://github.com/linuxserver/docker-letsencrypt/blob/master/README.md` and then some minimal changes in `prepare.sh`.  So for this project it seems, this will be a **wontfix** but it can be achieved easily for you personally. Maybe just fork the project and develop on this feature?
