### ISSUE TITLE
Logs not showing up

### ISSUE THREAD

**Issue by samderkaoui** [boschkundendienst/guacamole-docker-compose#106]
Hello :)

I have a small bug... i do active Screen recording or Typescript recording... everything works (and goes to /record => ./record on host machine...
but nothing show up in logs on guacamole interface (i tryed .guac / normal and mp4 for Screen recording just in case ^^)

![Guac1](https://github.com/user-attachments/assets/e70d53a0-4b53-46bd-85d9-afe5c4282e82)
![Guac2](https://github.com/user-attachments/assets/8c511178-c675-48c3-bc03-08fee8dc5620)

Any idea ? 

Big thanks

Sam

**Comment by boschkundendienst** [comment]
Hi, as [stated here](https://guacamole.apache.org/doc/gug/recording-playback.html)

**Each history entry has a deterministic, internal, unique identifier called its UUID, and all supported database backends make this UUID available ahead of time with the ${HISTORY_UUID} parameter token. This provides a reliable way for data stored outside the database to be associated with history entries that are otherwise stored purely inside the database, and it is this UUID that the extension searches for when locating the recording for a history entry.**

and

**When a user lists the history of a connection, the recording storage extension additionally [searches a predetermined location](https://guacamole.apache.org/doc/gug/recording-playback.html#recording-storage-config) for session recordings that match either of the following criteria:**

- The recording’s **filename is identical to the history entry UUID** and is directly within the search path.

- The recording has any name at all and is within a directory whose filename is identical to the history entry UUID and is directly within the search path.
So you have to somehow add the variable `${HISTORY_UUID}` to your **Recording Path**

For example in my setup I use the following for an RDP connection:
```
Recording Path: /drives_rec/${HISTORY_UUID}
Recording Name: ${GUAC_DATE}_${GUAC_TIME}_${GUAC_USERNAME:UPPER}_${GUAC_CLIENT_HOSTNAME:UPPER}_${GUAC_CLIENT_ADDRESS}_${HISTORY_UUID}.rec
```

As long as `${HISTORY_UUID}` can be found somewhere, the WebUI will show you the recordings and you can play them.

One additional thing to mention is, that the guacamole container needs read access to the recordings and the guacd container must be able write to the recording path.

**If you use a Linux distribution with SELinux enabled** you have to make sure, that the definition of the volume for your local recording path in guacd has a lower case `z` in its definition which means available also to other containers, while upper case `Z` means a private volume not available for other containers.

```yaml
...
GUACD
volumes:
    - ./record:/record:z

GUACAMOLE
    volumes:
      - ./record:/record:z
...
```

But I think in your case it is just about not having `${HISTORY_UUID}` in your recording name.

Hope I could help. Please close if it worked out for you.

**Comment by samderkaoui** [comment]
> Hi, as [stated here](https://guacamole.apache.org/doc/gug/recording-playback.html)
> 
> **Each history entry has a deterministic, internal, unique identifier called its UUID, and all supported database backends make this UUID available ahead of time with the ${HISTORY_UUID} parameter token. This provides a reliable way for data stored outside the database to be associated with history entries that are otherwise stored purely inside the database, and it is this UUID that the extension searches for when locating the recording for a history entry.**
> 
> and
> 
> **When a user lists the history of a connection, the recording storage extension additionally [searches a predetermined location](https://guacamole.apache.org/doc/gug/recording-playback.html#recording-storage-config) for session recordings that match either of the following criteria:**
> 
> * The recording’s **filename is identical to the history entry UUID** and is directly within the search path.
> * The recording has any name at all and is within a directory whose filename is identical to the history entry UUID and is directly within the search path.
>   So you have to somehow add the variable `${HISTORY_UUID}` to your **Recording Path**
> 
> **And this totally makes sense!. How should guacamole know, what the filename of a recording was and what should happen if you would record to the same file? - Using a UUID makes things clear and recordings unique and managable!**
> 
> For example in my setup I use the following for an RDP connection:
> 
> ```
> Recording Path: /drives_rec/${HISTORY_UUID}
> Recording Name: ${GUAC_DATE}_${GUAC_TIME}_${GUAC_USERNAME:UPPER}_${GUAC_CLIENT_HOSTNAME:UPPER}_${GUAC_CLIENT_ADDRESS}_${HISTORY_UUID}.rec
> ```
> 
> As long as `${HISTORY_UUID}` can be found somewhere, the WebUI will show you the recordings and you can play them.
> 
> One additional thing to mention is, that the guacamole container needs read access to the recordings and the guacd container must be able write to the recording path.
> 
> **If you use a Linux distribution with SELinux enabled** you have to make sure, that the definition of the volume for your local recording path in guacd has a lower case `z` in its definition which means available also to other containers, while upper case `Z` means a private volume not available for other containers.
> 
> ```yaml
> ...
> GUACD
> volumes:
>     - ./record:/record:z
> 
> GUACAMOLE
>     volumes:
>       - ./record:/record:z
> ...
> ```
> 
> But I think in your case it is just about not having `${HISTORY_UUID}` in your recording name.
> 
> Hope I could help. Please close if it worked out for you.



Thanks it worked fine ;)

have a nice day

Sam
