### ISSUE TITLE
Question - if I use portainer stack after running initial scripts will it work?

### ISSUE THREAD

**Issue by fate8383** [boschkundendienst/guacamole-docker-compose#33]
I kind of like using portainer and helps me since the server is at remote location so instead of docker compose up, will this work via portiner stack?

**Comment by boschkundendienst** [comment]
Theoretically it could work with portainer since it works with docker. It might be that you have to to do what prepare.sh does by hand (initializing the database) and maybe you could/should remove nginx. But you better look at the official documentation how to setup guacamole in docker [here](https://guacamole.apache.org/doc/gug/guacamole-docker.html).
