### ISSUE TITLE
SSH Keys

### ISSUE THREAD

**Issue by Jarvis-1487** [boschkundendienst/guacamole-docker-compose#37]
Most of my servers have SSH Password Auth disabled and I have been using SSH keys to manage them. Is there any way I can upload my SSH keys and use them for connections?

You can edit user-mapping.xml in Guacamole normally but the docker image doesnt have a text editor or permissions to install one.

I've been tearing my hair out, please can you provide assistance?

Thanks in advance, also great work!

**Comment by boschkundendienst** [comment]
Hi,
first of all, I am not a developer of Guacamole. I just use the official docker image they provide to have a "quick & dirty" fast way to spinup a guacamole server. The only purpose of this repo is to be able to do exactly that. It is also not good for production use.

That said. Concerning your problem you should contact the official [Guacamole developer team](https://guacamole.apache.org/support/).

Since the database backend uses the same options as previously in user-mapping.xml I think there will be a solution that will work for you.

I would recommend you ask your question on the official mailing list.

Kind regards

Peter

**Comment by Jarvis-1487** [comment]
Sorry! I posted this late at night and didn't think. In the morning I saw
that you were using the official Guac and Guacamole images so started
looking at their documentation.

It should be a case of logging in to the database and changing / adding the
values. Please close the ticket.

Alex
