### ISSUE TITLE
Handshake failed with Ubuntu 22.04-Clients

### ISSUE THREAD

**Issue by cablesky** [boschkundendienst/guacamole-docker-compose#40]
When trying to connect to an Ubuntu 22.04 server with this guacamole-Docker-Container, the error message "Handshake failed" appears in the log

**Comment by boschkundendienst** [comment]
Hi cablesky. Since I use the official containers from the Guacamole project, the error must be inside the official docker image(s). I would recommend you checkout their JIRA bug system [here](https://issues.apache.org/jira/projects/GUACAMOLE/issues/GUACAMOLE-1669?filter=allopenissues). Just searching for your error message brought a lot of results so the solution will be there.
