### ISSUE TITLE
locating log files fail2ban

### ISSUE THREAD

**Issue by Cah1982** [boschkundendienst/guacamole-docker-compose#59]
Hi in which container would you find the log for failed attempts to log in, and which folder in that container

thanks
 Carl

**Comment by boschkundendienst** [comment]
Since I use the official images provided by the Guacamole Project you should ask your question at their forums. One option you have is to run

```
docker-compose logs -f
```

to see all logs that are generated by docker during the run of the containers. All other things is not related to my project here. I would assume that you could enable logging with a custom guacamole.properties file that you inject into the container by changing the docker-compose.yml file to your needs.
This project is and has never been ment to be used in productive environments. It only exists to have a "quick and dirty" way to run Guacamole for the purpose of presenting it to someone.

I hope I could help.
