### ISSUE TITLE
wrong characters in RDP Sessions

### ISSUE THREAD

**Issue by Man-in-Black** [boschkundendienst/guacamole-docker-compose#6]
Hi,

I used this docker-Image to create my Guacamole inside docker.
But I noticed a problem:
If I want to type a colon, everytime it shows me a "Ö" (german layout).

I also changed the locale with an environment variable to "de_DE.UTF-8", but without any success.

do you have any advise for me?

Thanks.

Sascha

**Comment by boschkundendienst** [comment]
First of all, this is not a docker image, it is just a docker-compose yaml file that pulls official guacamole, nginx and postgres from dockerhub to combine it to a running guacamole instance. concerning your umlauts. Look at your language setting of the browser you access guacamole with. Then also you can set per connection keyboard layout etc.

If your OS types an `ö`  instead of  `:`  you have to fix this locally. It has nothing to do with guacamole neiter with this git repo!

**Comment by Man-in-Black** [comment]
sorry for this wrong wording.

I've tested it locally, there are no problems.
Also when I access an SSH Session there is no problem, only within RDP.
The problem exists also, when I type with the virtual keyboard from guacamole.
If I connect directly via RDP, without guacamole, there are no problems.

**Comment by boschkundendienst** [comment]
Have you specified the keyboard layout within Guacamole for that specific RDP connection?

Set the same keyboard layout there as your local keyboard has! It then should work!

**Comment by Man-in-Black** [comment]
I am heartbroken, unfortunately I missed the setting option.
I have now set the settings and can now write a colon.
Thank you for the quick help with this topic.

**Comment by boschkundendienst** [comment]
No problem, that is how community works!
